### ISSUE TITLE
MPL License and the App Store

### ISSUE THREAD

**Issue by mergesort** [regexident/Gestalt#1]
Hi Vincent,

I've been using Gestalt in an app and recently noticed that it was licensed MPL. I wasn't sure what that means with respect to shipping to the App Store and my source code. My app is for commercial purposes, and I plan to keep it closed source, but I'm still a bit confused as to what I need to do to be MPL compliant.

I was hoping you could clarify what needs to be done with my app (open source, display the copyright notice prominently, not be able to ship it at all, etc) to know whether I can use Gestalt.

Thanks a lot!

**Comment by regexident** [comment]
The primary reason why Apple don't allow GPL'd apps into their store is the fact that no additional restrictions may be applied. As stated in both other answers so far, this includes both Apple's TOS, and the fact that the TOS effectively disallows conveying the license along with the program.

With GPL, the license effectively applies to the entire program - most things you do with it are governed by the license. With the MPL, one's codebase is licensed, but nothing further: redistribution is permitted (including under other terms), and that's what Apple needs to legally publish your app in their store.

All [MPL-2.0 requires you to do](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)), as I'm concerned, is to make any changes you make to the source files included in *Gestalt* (they usually contain a short license comment at the top) open source under the same license. If you just include Gestalt via Carthage/CocoaPods/whatever then you don't need to do anything, other than include a license notice for *Gestalt* somewhere in your app.

> *Q9*: I want to distribute (outside my organization) MPL-licensed source code that I have modified. What do I have to do?
> To see the complete set of requirements, read the license. However, generally:
> 
> - You must inform the recipients that the source code is made available to them under the terms of the MPL (Section 3.1), including any Modifications (as defined in Section 1.10) that you have created.
> - You must make the grants described in Section 2 of the license.
> - You must respect the restrictions on removing or altering notices in the source code (Section 3.4).
> 
> *Q10*: I want to distribute (outside my organization) an executable program based on MPL-licensed source code that I have modified. What do I have to do?
> - You must make available the MPL-licensed portions of the source code as described in the previous question, and inform the recipients how they can obtain such source code (Section 3.2).

Source: [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)

Note that "MPL-licensed portions of the source code" only refers to files obtained from *Gestalt*. You own files are 100% your own and do not need to be made available as open source.

([IANAL](https://en.wikipedia.org/wiki/IANAL))

**Comment by mergesort** [comment]
@regexident Thanks a lot for the very thorough explanation. I really appreciate you taking the time and energy to make it clear.
