### ISSUE TITLE
Invalid Bundle Version String

### ISSUE THREAD

**Issue by TobiasRe** [regexident/Gestalt#11]
First of all, thanks for creating this awesome library! I adopted it quickly in my app. 
The current version however has an invalid _CFBundleShortVersionString_ of _2.0.0-b2_

Alpha-numeric appendix is not allowed.

Please update the info.plist so that the library can be directly used with Cocoapods/Carthage

Apple states: 

> Invalid or Non-Increasing `CFBundleShortVersionString` - The value specified in the bundle's Info.plist file for the key `CFBundleShortVersionString` must be a string consisting of at most three dot-separated components, where each component is composed only of the digits 0 through 9. For example, any of the following are syntactically valid values for `CFBundleShortVersionString`: `"1.0"`, `"4.2.1"`, `"3.46"`, `"1.112.0"`; whereas the following are all syntactically invalid: `"1.4.0.0.0.0.5"`, `"GX5"`, `"3.4.2b6"`, `"2.6GM"`, `"1.0 (Gold)"`, `"-3.6"`. Additionally, each updated version of the same application must have a `CFBundleShortVersionString` that increases relative to that of the previous version that was actually made available for sale on the iTunes Store. For example, if a previously-available version had a `CFBundleShortVersionString` of `"1.4"`, then any of the following would be acceptable as the next update: `"1.4.1"`, `"1.4.332"`, `"1.5"`; but all of the following (though syntactically valid) would be unacceptable: `"1.4"`, `"1.3"`, `"1.3.9"`, `"0.9"`. For more information about the `CFBundleShortVersionString` key and the Info.plist file, see Apple's [Runtime Configuration Guidelines](http://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPRuntimeConfig/index.html).

**Comment by regexident** [comment]
Version `2.0.0` should now be available via Carthage.

(No Cocoapods though, as `$ pod lib lint` keeps failing and I don't have time to look into it right now.)
