### ISSUE TITLE
How To Observe Themes Dynamically?

### ISSUE THREAD

**Issue by mergesort** [regexident/Gestalt#14]
In my app I change the currently selected theme, and save it to disk like so:
```swift
ThemeManager.default.theme = OfflineService.AppThemer.currentlySelectedColorScheme
// OfflineService.AppThemer.currentlySelectedColorScheme is a `ColorScheme` that conforms to `Theme`
```

The themes are dynamically downloaded from CloudKit, stored in the OfflineService, and then accessed when the user manually changes their theme.

Before when I used to be able to setup my app like this, and it would propagate whenever a change occurred:
```swift
ThemeManager.default.apply(theme: ColorScheme.self, to: self, animated: true) { viewController, colorScheme in
    self.view.backgroundColor = colorScheme.backgroundColor
}
```

Now I'm using the new API in version 2.0 like so, and changes aren't propagating when a theme change occurs:
```swift
func apply(theme: ColorScheme) {
    self.view.backgroundColor = theme.backgroundColor
}
```

I understand there needs to be some registration, such as `self.observe(theme: \ApplicationTheme.custom.stageDesign)` in the sample project, but since my themes don't get stored in source code, they're generated by downloading the themes, I'm not sure how to properly call `self.observe`.

I tried a few ideas, including `self.observe(theme: \OfflineService.appThemer.currentlySelectedColorScheme)`, but none of them seemed to work.

I can't seem to figure out if there's a way to observe the theme changes for something that doesn't exist in the source, and was wondering if you had any ideas.

Thanks a lot!

**Comment by regexident** [comment]
Where before with v1.x you had to do …

```swift
ThemeManager.default.apply(theme: AppTheme.self, to: self) { themeable, theme in
    themeable.view.backgroundColor = theme.view.backgroundColor
}
```

… in v2.x you now simply call …

```swift
self.observe(theme: \AppTheme.view)
```

… or …

```swift
ThemeManager.default.manage(theme: \AppTheme.view, for: self)
```

… which the former calls internally.

The latter, as you may notice, is very similar to 
 `ThemeManager`'s `func apply(theme:to:animated:closure:)` from v1.x.

The big difference to v1.x is that Gestalt now expects `self` to conform to `Themeable`, like so:

```swift
extension ViewController: Themeable {
    typealias Theme = ViewTheme

    func apply(theme: Theme) {
        self.view.backgroundColor = theme.backgroundColor
    }
}
```

The `\AppTheme.view` in …

```swift
self.observe(theme: \AppTheme.view)
```

… is a keypath to the relevant section of the theme, corresponding to `typealias Theme = ViewTheme`.

As such `AppTheme` would be expected to provide a `var view: ViewTheme { get }`.

The point of this being that `ViewController` is only ever exposed to `ViewTheme`, remaining unaware of `AppTheme`, aiming to improve encapsulation.

Please see the GestaltDemo project for more example usage or the [**Usage**](https://github.com/regexident/Gestalt#usage) section of the README for a full example.
