### ISSUE TITLE
Window hack not extension safe

### ISSUE THREAD

**Issue by heilerich** [regexident/Gestalt#15]
I'd like to use your library in a dynamic library which is shared between the main app and a today widget (which is also themeable). The problem is that your code won't compile when used in a target with extension safe API, because `UIApplication.shared.windows` is not available in app extensions and you are using it here:

https://github.com/regexident/Gestalt/blob/7e9093b1c821ec6e1edda17674ea34ec4faeef4d/Gestalt/ThemeManager.swift#L226-L235

Could you explain to me what this part of the code is doing? As I understand it from the comment this covers some kind of edge case? Is this strictly necessary?

I could provide code (and a PR) that will execute the above snippet only in environments where it is allowed and ignore it in environments where extension safe API is required. Thus, it would make your library usable in targets where only extension safe API is allowed. In my case this would mean using the same dynamic library would only execute the above snippet in my main app and not in the extension. Would this break anything?

**Comment by regexident** [comment]
This is why:

> "Note: iOS applies appearance changes when a view enters a window, it doesn’t change the appearance of a view that’s already in a window. To change the appearance of a view that’s currently in a window, remove the view from the view hierarchy and then put it back."

(From the [documentation of UIAppearance](https://developer.apple.com/documentation/uikit/uiappearance).)

---

If you can figure out a way to make things work with app extensions I'd welcome a PR! 🤩

Maybe this might help:

> I could just mention that `sharedApplication` actually exists in extensions, just artificially blocked due to how Apple have set up their extensions lifecycle. `UIApplication.value(forKey: "sharedApplication") as! UIApplication` will give you what you want. ;-)

(From [comment on StackOverflow](https://stackoverflow.com/questions/41388934/equivalent-of-uiapplication-shared-preferredcontentsizecategory-in-app-extension#comment69981017_41388934))

Or by detecting the app extension and disabling the code:

- [How to detect if code is running in Main App or App Extension Target?](https://stackoverflow.com/questions/25048026/how-to-detect-if-code-is-running-in-main-app-or-app-extension-target)

**Comment by heilerich** [comment]
Oh I see, the appearance proxy is the problem. Thanks for the clarification! I should have thought of that myself. When reading your code comment my brain didn't parse 'appearance'  to `UIAppearance` 😅

I think I have a working version, disabling the code in extensions if `sharedApplication` is not accessible. I guess this will delay delay changing the theme in the extension a little bit, but since extensions are reloaded by the OS quite frequently anyways I think this shouldn't be a problem. I will test for a few more days and drop you a PR as soon as I get round to it.

**Comment by regexident** [comment]
Great, looking forward to it!
