### ISSUE TITLE
Unsubscribe from theme update?

### ISSUE THREAD

**Issue by ton252** [regexident/Gestalt#22]
How can we unsubscribe from theme manager updates for specific view? (If I used manage<T, U> method)

**Comment by regexident** [comment]
The `func manage` API is intended for "call once and forget" theme management.
As such it does not allow for unsubscribing. That's what `func observe` is for.

To make things a bit easier I just added a variant of `func observe` that accepts the same arguments as `func manage`, while returning a `Disposable`: https://github.com/regexident/Gestalt/pull/24
