### ISSUE TITLE
UIAppearance not working.

### ISSUE THREAD

**Issue by kylebrowning** [regexident/Gestalt#7]
I may be seeing things wrong but how does the `UIAppearance` work?

I get `Type 'UINavigationBar' has no member 'apply'`

**Comment by regexident** [comment]
Calling [`UINavigationBar.apply(theme: theme)`](https://github.com/regexident/Gestalt/blob/e1f9537cff99ad48fb406fd7c0afe8beb1465e01/GestaltDemo/AppDelegate.swift#L34) will only work if you made the corresponding theme conform to `AppearanceTheme`:

```struct
struct NavigationBarTheme: AppearanceTheme {
    typealias View = UINavigationBar

    // ...

    func theme(_ klass: View.Type) {
        let proxy = klass.appearance()
        
        proxy.tintColor = self.tintColor
        // ...
    }
}

extension NavigationBarTheme.View: AppearanceThemeView {}
```

Example: [NavigationBarTheme.swift](https://github.com/regexident/Gestalt/blob/b1581cf9e0b51b5f9339fa633178cded4fb7df44/GestaltDemo/Themes/UIAppearance/NavigationBarTheme.swift).
