### ISSUE TITLE
Initial theme apply?

### ISSUE THREAD

**Issue by mario-deluna** [regexident/Gestalt#9]
I'm probably misunderstood something but how do I apply the styling initially?

As soon as a view registers the observer in its `viewDidLoad` method the theme switching obviously works, but how should the theme be applied initially?

I first thought to simply call `apply` initially the same way as observe but that results in an error:

```swift
self.apply(theme: \MyTheme.view)
self.observe(theme: \MyTheme.view)
```

And storing the current theme somewhere and applying it from there seems wrong, like im missing the intended implementation:

```swift
self.apply(theme: Somewhere.currenTheme.view)
```

Kind regards 
Mario

**Comment by regexident** [comment]
`self.observe(theme: \MyTheme.view)` will ensure that `self.apply(theme: \MyTheme.view)` is executed immediately (if a theme has been chosen at that point).

To choose a theme you assign a value to `ThemeManager.default.theme` early during your app's launch (e.g. in `AppDelegate`'s `func application(_:didFinishLaunchingWithOptions:)`):

(Gestalt includes a `GestaltDemo` target which should give you an idea of how Gestalt works.)

👉🏻 [GestaltDemo/AppDelegate.swift](https://github.com/regexident/Gestalt/blob/master/GestaltDemo/AppDelegate.swift#L30-L35)

With v2.x all you should have to do is run `self.observe(theme: \MyTheme.view)` once in an object's lifetime. The `ThemeManager` then makes sure that `self.apply(theme: \MyTheme.view)` is executed on every theme-observing object once its theme is changed.

**Comment by mario-deluna** [comment]
The GestaltDemo is really helpful thanks, I think what god me confused is this part in the Readme: 

```swift
class ViewController: UIViewController {
    @IBOutlet var label: UILabel!

    override func viewDidLoad() {
        super.viewDidLoad()
	self.observe(theme: \Theme.view)
    }
}
```

This way apply is not being called initially, if the view controller is being loaded after a the theme has been set.

**Comment by regexident** [comment]
The README mentions it:

```
// In `AppDelegate.application(_:didFinishLaunchingWithOptions:)`
// assign a default theme (or user's choice from user defaults):
ThemeManager.default.theme = Theme.light
```

But you're right, it could —and should— be much clearer! 🙈

I just pushed the first beta for v2.0.0 a couple of days ago and haven't gotten to improving the README yet. I'll make sure to improve the README!

If you have any further questions or things that might be made clearer, lemme know and I'll make sure to include them in the documentation improvements.
